<a href="https://colab.research.google.com/github/dekoska/neural-network-course/blob/main/02_keras%20/01_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(units=4, input_shape=(10,))) #np 10 zmiennych
model.add(Dense(units=2))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 4)              │            44 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 2)              │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 54 (216.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

### Funkcje aktywacji

In [7]:
from tensorflow.keras.activations import linear

random_data = sorted(np.random.randn(200))
data = pd.DataFrame({'data':random_data, 'linear':linear(random_data)})
data.head()

data    linear
0 -2.684921 -2.684921
1 -2.314536 -2.314536
2 -2.086028 -2.086028
3 -2.078794 -2.078794
4 -2.006519 -2.006519

In [8]:
px.line(data, x='data', y='linear', width=800, range_y=[-2,2])

In [9]:
from tensorflow.keras.layers import Activation
from tensorflow.keras.activations import sigmoid

# model.add(Dense(units=, activation='sigmoid'))
# model.add(Activation('tahn'))

data = pd.DataFrame({'data':random_data, 'sigmoid':sigmoid(random_data)})
data.head()

data   sigmoid
0 -2.684921  0.063869
1 -2.314536  0.089926
2 -2.086028  0.110462
3 -2.078794  0.111175
4 -2.006519  0.118520

In [10]:
px.line(data, x='data', y='sigmoid', width=800, range_y=[-0.5,1.5])

In [12]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data':random_data, 'relu':relu(random_data)})
data.head()

data  relu
0 -2.684921   0.0
1 -2.314536   0.0
2 -2.086028   0.0
3 -2.078794   0.0
4 -2.006519   0.0

In [13]:
px.line(data, x='data', y='relu', width=800, range_y=[-0.5,1.5])

In [14]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data':random_data, 'tanh':tanh(random_data)})
data.head()

data      tanh
0 -2.684921 -0.990733
1 -2.314536 -0.980661
2 -2.086028 -0.969627
3 -2.078794 -0.969192
4 -2.006519 -0.964485

In [16]:
px.line(data, x='data', y='tanh', width=800, range_y=[-1.5,1.5])

In [21]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

In [ ]:
#model.fit(data, labels, epochs=1 0, batch_size=32, validation_data=(x_val, y_val))

###Klasyfikacja binarna przykład

In [24]:
data = np.random.randn(1000, 150)
labels = np.random.randint(2, size=(1000,1))

print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [26]:
data[:3]

array([[-1.02593701,  0.46226597, -0.80195201,  1.49265489, -0.4854077 ,
         1.62806802,  1.35901354,  0.5959779 , -2.90648872,  0.25187307,
        -0.12812491, -0.27687544, -0.12807792,  0.59003683, -1.27194859,
        -1.36237432, -0.39813003,  1.24958507, -1.29981572, -0.23990383,
        -1.13611869,  1.08766234, -0.02663454,  0.45913408,  0.23397732,
         0.23299785,  2.22331955,  0.10879648, -0.97436648,  1.63349473,
        -1.45284141, -0.34213579,  1.09625457,  2.53470637, -0.25312801,
        -0.96865403, -0.15162236, -0.07478283, -0.58823676,  2.42499077,
         1.15202478,  0.01662604, -0.68769944,  0.86348874,  0.94538313,
         0.40875822, -0.08523057,  1.0386758 ,  0.89758576,  1.25378627,
        -0.20524858, -0.52056459,  0.71160161, -0.01567913,  0.62431733,
         1.19830218, -0.77026984, -0.10577324, -1.36783397, -1.77575513,
        -1.60484762,  0.32109763,  0.02834805,  0.95202511,  0.2096634 ,
         0.62174558, -0.9896307 ,  0.70644098,  1.7

In [28]:
labels[:10]

array([[1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1]])

In [29]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5041 - loss: 0.8297
Epoch 2/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5471 - loss: 0.7356
Epoch 3/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6657 - loss: 0.6356
Epoch 4/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6705 - loss: 0.6197
Epoch 5/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7168 - loss: 0.5896
Epoch 6/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7456 - loss: 0.5488
Epoch 7/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7604 - loss: 0.5359
Epoch 8/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7907 - loss: 0.5138
Epoch 9/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7999 - loss: 0.4969
Epoch 10/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8175 - loss: 0.4787
Epoch 11/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8486 - loss: 0.4417
Epoch 12/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8734 - loss: 0.4091


In [30]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



Epoch 1/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4744 - loss: 0.9172
Epoch 2/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6017 - loss: 0.7045
Epoch 3/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6073 - loss: 0.6695
Epoch 4/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6622 - loss: 0.6333
Epoch 5/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7280 - loss: 0.5751
Epoch 6/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7491 - loss: 0.5447
Epoch 7/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7869 - loss: 0.5111
Epoch 8/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8153 - loss: 0.4875
Epoch 9/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8325 - loss: 0.4741
Epoch 10/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8530 - loss: 0.4467
Epoch 11/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8606 - loss: 0.4229
Epoch 12/20
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8905 - lo

In [31]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30, validation_split=0.2)

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.5268 - loss: 0.7918 - val_accuracy: 0.4750 - val_loss: 0.7817
Epoch 2/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5910 - loss: 0.6966 - val_accuracy: 0.4600 - val_loss: 0.7711
Epoch 3/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6064 - loss: 0.6559 - val_accuracy: 0.4550 - val_loss: 0.7742
Epoch 4/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6874 - loss: 0.5913 - val_accuracy: 0.4650 - val_loss: 0.7822
Epoch 5/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7155 - loss: 0.5672 - val_accuracy: 0.4600 - val_loss: 0.7908
Epoch 6/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7822 - loss: 0.5217 - val_accuracy: 0.4650 - val_loss: 0.8034
Epoch 7/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7872 - loss: 0.5079 - val_accuracy: 0.4550 - val_loss: 0.8175
Epoch 8/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7984 - loss: 0.4740 - val_accuracy: 0.4600 - val_loss: 0.8338
Ep

In [32]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=30, validation_split=0.2, verbose=0)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



In [33]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=30, validation_split=0.2, verbose=0)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



In [34]:
metrics = history.history
metrics.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [35]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=30, validation_split=0.2, verbose=1)

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 0.5007 - loss: 0.7989 - val_accuracy: 0.5250 - val_loss: 0.7758
Epoch 2/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5900 - loss: 0.6940 - val_accuracy: 0.5350 - val_loss: 0.7702
Epoch 3/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6085 - loss: 0.6598 - val_accuracy: 0.5300 - val_loss: 0.7703
Epoch 4/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6614 - loss: 0.6170 - val_accuracy: 0.5100 - val_loss: 0.7726
Epoch 5/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7462 - loss: 0.5548 - val_accuracy: 0.5000 - val_loss: 0.7787
Epoch 6/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7211 - loss: 0.5542 - val_accuracy: 0.5050 - val_loss: 0.7877
Epoch 7/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7797 - loss: 0.5224 - val_accuracy: 0.4850 - val_loss: 0.7980
Epoch 8/20
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8146 - loss: 0.4839 - val_accuracy: 0.4900 - val_loss: 0.8097
Ep

In [36]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5,1))

In [37]:
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step


array([[0.8791107 ],
       [0.90267575],
       [0.7936085 ],
       [0.14133553],
       [0.86358696]], dtype=float32)

In [40]:
predictions = (model.predict(test_data) > 0.5).astype("int32")
predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step


array([[1],
       [1],
       [1],
       [0],
       [1]], dtype=int32)

###Klasyfikacja wieloklasowa przykład

In [49]:
from tensorflow.keras.utils import to_categorical

data = np.random.randn(1000, 150)
labels = np.random.randint(2, size=(1000,1))
labels = to_categorical(labels, num_classes=10)

labels[1]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.1523 - loss: 2.2930 - val_accuracy: 0.3250 - val_loss: 1.8885
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4103 - loss: 1.6647 - val_accuracy: 0.4650 - val_loss: 1.4837
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5419 - loss: 1.2713 - val_accuracy: 0.4900 - val_loss: 1.2232
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5875 - loss: 1.0070 - val_accuracy: 0.5050 - val_loss: 1.0650
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6422 - loss: 0.8256 - val_accuracy: 0.5150 - val_loss: 0.9696
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6890 - loss: 0.6988 - val_accuracy: 0.5050 - val_loss: 0.9117
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6899 - loss: 0.6472 - val_accuracy: 0.5150 - val_loss: 0.8796
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7494 - loss: 0.5528 - val_accuracy: 0.4950 - val_loss

In [51]:
test_data = np.random.randn(10, 150)

In [52]:
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[1.8422954e-01, 8.1379676e-01, 1.9539252e-04, 1.2942620e-04,
        1.6764816e-04, 2.2576099e-04, 7.7745281e-05, 1.0486223e-04,
        5.5328803e-04, 5.1959575e-04],
       [8.6695457e-01, 1.3273165e-01, 3.4849911e-06, 4.1347444e-05,
        2.6709617e-05, 2.4591085e-05, 1.6946017e-06, 1.9127362e-04,
        1.5487676e-05, 9.2021719e-06],
       [8.0879986e-01, 1.9119541e-01, 2.6595745e-07, 5.4370616e-07,
        3.0587904e-07, 1.6484510e-06, 4.1382080e-07, 1.0087211e-06,
        2.3778804e-07, 2.0877330e-07],
       [8.1123638e-01, 1.8860699e-01, 7.2803582e-06, 3.3539953e-05,
        7.5654957e-06, 4.2096621e-05, 1.0811729e-05, 3.5030538e-05,
        6.9450780e-06, 1.3443524e-05],
       [8.5349363e-01, 1.4353071e-01, 4.3550445e-04, 1.1107301e-03,
        1.4861829e-04, 1.5147122e-04, 5.4110290e-04, 1.0188488e-04,
        1.5935994e-04, 3.2694874e-04],
       [1.1246185e-01, 8.8748902e-01, 3.4522338e-05, 7.0178766e-07,
        1.9033879e-06, 3.5396683e-06, 3.8014123e-06, 2.91

In [53]:
predictions = (model.predict(test_data) > 0.5).astype("int32")
predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

### Regresja przykład

In [63]:
data = np.random.random((1000, 150))
labels = 50 * np.random.random(1000)

data[:3]

array([[0.8943834 , 0.87604485, 0.50512747, 0.97759518, 0.8273141 ,
        0.23803719, 0.97237707, 0.76277817, 0.63076828, 0.97085674,
        0.87213835, 0.9188494 , 0.85386895, 0.44050066, 0.30857642,
        0.85550298, 0.10832618, 0.68917726, 0.50108026, 0.70764329,
        0.85550465, 0.95672453, 0.12482557, 0.30635534, 0.97626511,
        0.47960135, 0.75301692, 0.62192185, 0.87370002, 0.40643269,
        0.0885365 , 0.12243052, 0.15084579, 0.08485531, 0.6470807 ,
        0.38759776, 0.69752127, 0.13166516, 0.69572031, 0.32501525,
        0.38345002, 0.34861689, 0.39643037, 0.22867454, 0.07623983,
        0.96356772, 0.55565671, 0.3653918 , 0.46742839, 0.95556876,
        0.28359198, 0.83709705, 0.63523699, 0.07278701, 0.74638407,
        0.91830517, 0.70453379, 0.75050031, 0.1395329 , 0.88395654,
        0.90997097, 0.21512258, 0.70935154, 0.11922339, 0.18506508,
        0.18449315, 0.08964491, 0.32323508, 0.77346393, 0.85971879,
        0.95680874, 0.07085869, 0.9372283 , 0.65

In [64]:
labels[:3]

array([2.43269185, 7.9257178 , 0.95979719])

In [65]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 651.8070 - val_loss: 446.5581
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 382.1921 - val_loss: 289.0773
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 262.5052 - val_loss: 232.8095
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 214.3467 - val_loss: 227.6985
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 213.7322 - val_loss: 227.0802
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 208.5828 - val_loss: 227.2356
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 206.8212 - val_loss: 227.3707
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 199.9649 - val_loss: 227.2005
Epoch 9/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 214.6490 - val_loss: 227.4122
Epoch 10/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 200.8150 - val_loss: 227.2077
Epoch 11/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 199.3596 - val_loss: 227.4431
Epoch 12/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0

In [66]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 20.3282 - mse: 594.8352 - val_loss: 15.8053 - val_mse: 370.9448
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14.5125 - mse: 304.2837 - val_loss: 13.5890 - val_mse: 244.6085
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13.1622 - mse: 230.2570 - val_loss: 13.2506 - val_mse: 229.4245
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.5464 - mse: 210.2929 - val_loss: 13.1551 - val_mse: 226.7524
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.6015 - mse: 209.0534 - val_loss: 13.1689 - val_mse: 227.0042
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.3628 - mse: 205.1033 - val_loss: 13.1842 - val_mse: 227.3218
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12.4406 - mse: 209.4272 - val_loss: 13.2037 - val_mse: 228.4141
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.3771 - mse: 201.8510 - val_loss: 13.2064 - val_mse: 228.4400
Epoch 9/30
25/25 ━━━━━━

In [67]:
test_data = np.random.random((10, 150))
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step


array([[25.821785],
       [21.842873],
       [27.045065],
       [19.59163 ],
       [25.169394],
       [23.393059],
       [24.846811],
       [30.203901],
       [27.3617  ],
       [26.905333]], dtype=float32)