<a href="https://colab.research.google.com/github/dekoska/neural-network-course/blob/main/02_basics/01_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
scalar = 3
print(type(scalar))

<class 'int'>


In [3]:
vector = np.array([2,3,-6,5])
print(vector)
print(type(vector))
print(f"rozmiar wektora: {vector.shape}")
print(f"typ danych wektora: {vector.dtype}")
print(f"rzad: {vector.ndim}")
print(f"dlugosc: {len(vector)}")

[ 2  3 -6  5]
<class 'numpy.ndarray'>
rozmiar wektora: (4,)
typ danych wektora: int64
rzad: 1
dlugosc: 4


In [5]:
vector = np.array([2,4,-6,5], dtype='float')
print(vector)
print(f"typ danych wektora: {vector.dtype}")

[ 2.  4. -6.  5.]
typ danych wektora: float64


In [6]:
array = np.array([[2,6,3],
                  [5,3,4],
                  [4,2,1]], dtype='float')

print(array)
print(f"rozmiar macierzy: {array.shape}")
print(f"typ danych macierzy: {array.dtype}")
print(f"rzad: {array.ndim}")
print(f"dlugosc: {len(array)}")

[[2. 6. 3.]
 [5. 3. 4.]
 [4. 2. 1.]]
rozmiar macierzy: (3, 3)
typ danych macierzy: float64
rzad: 2
dlugosc: 3


In [7]:
tensor = np.array([
    [[1,2,3],
     [4,5,6]],
     [[7,8,9],
      [3,7,3]]
])

print(tensor)
print(f"rozmiar macierzy: {tensor.shape}")
print(f"typ danych macierzy: {tensor.dtype}")
print(f"rzad: {tensor.ndim}")
print(f"dlugosc: {len(tensor)}")

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [3 7 3]]]
rozmiar macierzy: (2, 2, 3)
typ danych macierzy: int64
rzad: 3
dlugosc: 2


In [8]:
tensor[0]

array([[1, 2, 3],
       [4, 5, 6]])