<a href="https://colab.research.google.com/github/dekoska/neural-network-course/blob/main/01_basics/05_regression_metrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import tensorflow as tf

In [2]:
y_true = 100 + 20 * np.random.randn(50)
y_true

array([ 86.35466165, 124.2805131 ,  72.51110361, 111.43746173,
       136.52788865, 127.26590942,  67.94917821,  86.87798944,
       132.10740424, 101.52311088,  60.62980723, 119.46594991,
       104.17256791,  82.93669047,  78.52433603, 107.31301992,
       110.87084724, 127.19788736,  77.03532608, 129.16063042,
        77.76944049, 104.33881357, 103.53944067, 114.7177753 ,
       120.28113442,  93.49681425,  96.19156188,  71.02664514,
       117.60810196, 113.20063363,  67.3715558 ,  68.53410261,
       100.44619658, 103.3386971 ,  78.41252591,  96.61284973,
        66.44487183,  93.43810124, 105.05779267,  96.72371892,
        91.52379981, 109.73833748,  92.03738998,  90.06280266,
       112.8444111 ,  83.17612577, 100.92558636, 150.2192694 ,
        77.89412158, 112.94680095])

In [3]:
y_pred = y_true + 10 * np.random.randn(50)
y_pred

array([ 94.37641588, 130.16880034,  68.37951704, 123.59277216,
       130.59519268, 128.23276337,  60.24195083,  91.45271358,
       138.09684019, 114.77786937,  71.67853075, 123.3720316 ,
        88.09044259, 110.75024864,  85.27173649, 107.37514029,
       108.90897258, 120.46546176,  78.44030486, 123.97993202,
        79.09227316,  99.69486185, 109.70443572, 110.89696674,
       107.96408866,  79.63862874, 107.48379522,  63.76953605,
        95.18236214,  93.49487716,  91.56464628,  65.47067713,
        85.36249721,  96.70024137,  73.3134414 ,  80.63944878,
        76.35742406,  91.79230234, 101.14539786,  89.7840836 ,
        84.92442174, 100.1045499 ,  86.80662394,  93.68363141,
       105.96895092,  79.4776872 , 102.35349158, 146.21911093,
        81.1017804 , 123.46707097])

In [7]:
results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
results.head()

y_true      y_pred
0   86.354662   94.376416
1  124.280513  130.168800
2   72.511104   68.379517
3  111.437462  123.592772
4  136.527889  130.595193

In [8]:
results['error'] = results['y_true'] - results['y_pred']
results.head()

y_true      y_pred      error
0   86.354662   94.376416  -8.021754
1  124.280513  130.168800  -5.888287
2   72.511104   68.379517   4.131587
3  111.437462  123.592772 -12.155310
4  136.527889  130.595193   5.932696

###Metryki

In [9]:
def plot_regression_results(y_true, y_pred):
    results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
    min = results[['y_true', 'y_pred']].min().min()
    max = results[['y_true', 'y_pred']].max().max()

    fig = go.Figure(data=[go.Scatter(x=results['y_true'], y=results['y_pred'], mode='markers'),
                    go.Scatter(x=[min, max], y=[min, max])],
                    layout=go.Layout(showlegend=False, width=800,
                                     xaxis_title='y_true',
                                     yaxis_title='y_pred',
                                     title='Regression results'))
    fig.show()
plot_regression_results(y_true, y_pred)

In [10]:

y_true = 100 + 20 * np.random.randn(1000)
y_pred = y_true + 10 * np.random.randn(1000)
results = pd.DataFrame({'y_true': y_true, 'y_pred': y_pred})
results['error'] = results['y_true'] - results['y_pred']

px.histogram(results, x='error', nbins=50, width=800)

In [11]:
#MAE
def mean_absolute_error(y_true, y_pred):
    return abs(y_true - y_pred).sum() / len(y_true)

mean_absolute_error(y_true, y_pred)

np.float64(8.13569362541321)

In [15]:
from tensorflow.keras.losses import MeanAbsoluteError

mae = MeanAbsoluteError()
mae(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=8.135692596435547>

In [17]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_true, y_pred)
mae

8.13569362541321

In [18]:
#MSE
def mean_squared_error(y_true, y_pred):
    return ((y_true - y_pred) ** 2).sum() / len(y_true)

mean_squared_error(y_true, y_pred)

np.float64(104.0714611612149)

In [19]:
from tensorflow.keras.losses import MeanSquaredError

mse = MeanSquaredError()
mse(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float32, numpy=104.07145690917969>

In [20]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_true, y_pred)
mse

104.0714611612149

In [21]:
#rmse
def root_mean_squared_error(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

root_mean_squared_error(y_true, y_pred)

np.float64(10.201542097213288)

In [24]:
np.sqrt(mean_squared_error(y_true, y_pred))

np.float64(10.201542097213288)

In [25]:
#max error
def max_error(y_true, y_pred):
    return abs(y_true - y_pred).max()

max_error(y_true, y_pred)

np.float64(33.397492416906005)

In [26]:
from sklearn.metrics import max_error

max_error(y_true, y_pred)

np.float64(33.397492416906005)

In [27]:
#r2 score
from sklearn.metrics import r2_score

r2_score(y_true, y_pred)

0.7377271952697311

In [28]:
def r2_score(y_true, y_pred):
  nominator = ((y_true - y_pred) ** 2).sum()
  denominator = ((y_true - y_true.mean()) ** 2).sum()

  try:
    r2 = 1 - (nominator / denominator)
  except ZeroDivisionError:
    print('dzielenie przez zero matole')
  return r2

r2_score(y_true, y_pred)

np.float64(0.7377271952697311)