<a href="https://colab.research.google.com/github/dekoska/neural-network-course/blob/main/02_basics%20/02_activation_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

### ReLU

In [4]:
def max_relu(x):
  return max(x,0.0)

for i in [-10., -5., 0., 5., 10.]:
  print(max_relu(i)) #zeruje wartosci ujemne

0.0
0.0
0.0
5.0
10.0


In [6]:
data = np.random.randn(50)
data = sorted(data)
data

[np.float64(-2.8121428685120433),
 np.float64(-1.7505538201282018),
 np.float64(-1.6846822271739699),
 np.float64(-1.5892066534204554),
 np.float64(-1.5595688677744992),
 np.float64(-1.4694060564600195),
 np.float64(-1.3399484448031183),
 np.float64(-0.9541379214752582),
 np.float64(-0.9476482056165151),
 np.float64(-0.8542867772504631),
 np.float64(-0.7505181920651449),
 np.float64(-0.4719193477804564),
 np.float64(-0.44766928823655605),
 np.float64(-0.2561243521708745),
 np.float64(-0.2536630579731406),
 np.float64(-0.21007046696168874),
 np.float64(-0.1927536062760099),
 np.float64(-0.13171926719456034),
 np.float64(-0.09968791164816987),
 np.float64(-0.09523841335091855),
 np.float64(-0.07421663037251376),
 np.float64(-0.07098149217536627),
 np.float64(-0.03044915106483644),
 np.float64(0.06845112394441508),
 np.float64(0.1440624162765174),
 np.float64(0.28681901219882056),
 np.float64(0.2918606860549062),
 np.float64(0.32129111537100175),
 np.float64(0.384689709782048),
 np.float6

In [7]:
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.06845112, 0.14406242,
       0.28681901, 0.29186069, 0.32129112, 0.38468971, 0.39407336,
       0.42010291, 0.51512487, 0.55998408, 0.70934803, 0.81218   ,
       1.05621645, 1.0593151 , 1.08962654, 1.17481818, 1.2653488 ,
       1.32685884, 1.48391797, 1.54014281, 1.57552133, 1.65326668,
       1.67875131, 1.84885717, 2.09663338, 2.41869166, 2.65685976])

In [8]:
df = pd.DataFrame({'data':data, 'max_relu':max_relu_data})
df.head()

data  max_relu
0 -2.812143       0.0
1 -1.750554       0.0
2 -1.684682       0.0
3 -1.589207       0.0
4 -1.559569       0.0

In [11]:
px.line(df, x='data', y='max_relu', width=700, height=400, title='relu function')

### Sigmoid

In [14]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

for i in [-5., -3., -1., 0., 1., 3., 5]:
  print(sigmoid(i))

0.0066928509242848554
0.04742587317756678
0.2689414213699951
0.5
0.7310585786300049
0.9525741268224334
0.9933071490757153


In [18]:
data = 3 * np.random.randn(50)
data = sorted(data)
data

[np.float64(-6.589245371100475),
 np.float64(-5.18557722863327),
 np.float64(-4.847906302856778),
 np.float64(-4.713686260777817),
 np.float64(-4.553985435448789),
 np.float64(-4.464846659496786),
 np.float64(-4.172540301880354),
 np.float64(-3.9603974767710515),
 np.float64(-3.617827662527747),
 np.float64(-3.285850060916365),
 np.float64(-3.0083689711683563),
 np.float64(-2.350787161868285),
 np.float64(-2.2916868629494616),
 np.float64(-2.2438589366598594),
 np.float64(-2.2173585057148912),
 np.float64(-2.1521987663898483),
 np.float64(-1.8650945405114352),
 np.float64(-1.3983513872479831),
 np.float64(-1.249569528425091),
 np.float64(-0.993289404958434),
 np.float64(-0.886383949448539),
 np.float64(-0.827199942222983),
 np.float64(-0.792214886126722),
 np.float64(-0.708464830876505),
 np.float64(-0.6568879813573356),
 np.float64(-0.3992489689600438),
 np.float64(-0.052015016509008215),
 np.float64(0.030075718251651375),
 np.float64(0.24224186761925914),
 np.float64(0.34365883831889

In [21]:
sigmoid_data = [sigmoid(x) for x in data]
sigmoid_data

[np.float64(0.0013731890042658226),
 np.float64(0.005565556326797267),
 np.float64(0.007783723335190589),
 np.float64(0.008891870030808892),
 np.float64(0.01041554783879908),
 np.float64(0.011375567518113186),
 np.float64(0.015179100204433268),
 np.float64(0.01869921503725924),
 np.float64(0.026139317397974846),
 np.float64(0.036059818322668316),
 np.float64(0.047049219817847585),
 np.float64(0.08700322495840207),
 np.float64(0.09181379562918146),
 np.float64(0.09588049834053874),
 np.float64(0.09820248359449828),
 np.float64(0.10412593539298341),
 np.float64(0.13411034610658273),
 np.float64(0.19807785172257525),
 np.float64(0.22277466441053634),
 np.float64(0.2702628484016364),
 np.float64(0.29185661660816575),
 np.float64(0.3042374529771816),
 np.float64(0.3116932883810785),
 np.float64(0.3299381451426157),
 np.float64(0.34143902945079235),
 np.float64(0.4014927965317953),
 np.float64(0.4869991769515852),
 np.float64(0.5075183628442648),
 np.float64(0.5602660481189554),
 np.float64(

In [22]:
df = pd.DataFrame({'data':data, 'sigmoid':sigmoid_data})
df.head()

data   sigmoid
0 -6.589245  0.001373
1 -5.185577  0.005566
2 -4.847906  0.007784
3 -4.713686  0.008892
4 -4.553985  0.010416

In [24]:
px.line(df, x='data', y='sigmoid', width=700, height=400, title='sigmoid function')

### Tahn

In [29]:
def tahn(x):
  return ((np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x)))

data = 2 * np.random.randn(100)
data = sorted(data)
data

[np.float64(-5.982832291278381),
 np.float64(-4.869553313075693),
 np.float64(-4.618676375621531),
 np.float64(-4.618059845165899),
 np.float64(-4.031271186235081),
 np.float64(-3.8615352893489576),
 np.float64(-3.378457427927306),
 np.float64(-3.3605568677348523),
 np.float64(-3.252087473551607),
 np.float64(-2.9076829011505128),
 np.float64(-2.894601839328325),
 np.float64(-2.754743254385423),
 np.float64(-2.7345807992725777),
 np.float64(-2.6429127975138855),
 np.float64(-2.6416467677347533),
 np.float64(-2.551615065763693),
 np.float64(-2.2066415656211325),
 np.float64(-2.1612975899123783),
 np.float64(-2.1322222543665243),
 np.float64(-1.8763305792940759),
 np.float64(-1.837500413038167),
 np.float64(-1.7994442441238012),
 np.float64(-1.7654940630415479),
 np.float64(-1.73423109413779),
 np.float64(-1.4313503132710925),
 np.float64(-1.3992204915027875),
 np.float64(-1.2694238060580647),
 np.float64(-1.2547189498973128),
 np.float64(-1.240428385279478),
 np.float64(-1.1430078199837

In [30]:
tahn_data = [tahn(x) for x in data]
tahn_data

[np.float64(-0.9999872824008104),
 np.float64(-0.9998821406244749),
 np.float64(-0.9998053491079089),
 np.float64(-0.9998051089668671),
 np.float64(-0.9993699493007966),
 np.float64(-0.999115391868294),
 np.float64(-0.9976770789473121),
 np.float64(-0.9975925110989119),
 np.float64(-0.9970101253705),
 np.float64(-0.9940549454656858),
 np.float64(-0.9938978386008482),
 np.float64(-0.9919362723510231),
 np.float64(-0.991605850677937),
 np.float64(-0.9899253054772523),
 np.float64(-0.9898998924160662),
 np.float64(-0.9879192456834459),
 np.float64(-0.9760593752846056),
 np.float64(-0.9738165094059621),
 np.float64(-0.9722705175293626),
 np.float64(-0.9541645915088887),
 np.float64(-0.9505546402750922),
 np.float64(-0.946748429377277),
 np.float64(-0.9431134623192425),
 np.float64(-0.9395539568585524),
 np.float64(-0.8919429867023877),
 np.float64(-0.885183039194235),
 np.float64(-0.8536414107137315),
 np.float64(-0.8496016180017193),
 np.float64(-0.8455777290381075),
 np.float64(-0.815424

In [31]:
df = pd.DataFrame({'data':data, 'tahn':tahn_data})
df.head()

data      tahn
0 -5.982832 -0.999987
1 -4.869553 -0.999882
2 -4.618676 -0.999805
3 -4.618060 -0.999805
4 -4.031271 -0.999370

In [32]:
px.line(df, x='data', y='tahn', width=700, height=400, title='tahn function')

### Softmax

In [36]:
def softmax(x):
  e_x = np.exp(x)
  denominator = np.sum(e_x, axis=1)
  denominator = denominator[:, np.newaxis]
  return e_x / denominator

data = np.random.randn(4,5)
data

array([[ 0.16427811, -1.07306617,  1.4419151 , -0.87790043,  0.75912322],
       [ 0.11501617, -1.85730034,  0.51082732,  1.17840359, -1.92061349],
       [-0.9502388 ,  0.08042337, -1.70249886, -0.72209333,  0.16640717],
       [ 1.00733866,  0.62547811,  0.82435243,  0.6367856 , -0.32625681]])

In [37]:
result = softmax(data)
result

array([[0.14197003, 0.04119314, 0.50940988, 0.05007077, 0.25735619],
       [0.17694461, 0.02461904, 0.26286692, 0.51246077, 0.02310865],
       [0.11648113, 0.32648744, 0.05489758, 0.14633153, 0.35580232],
       [0.28824671, 0.19675439, 0.24004599, 0.19899181, 0.07596109]])

In [38]:
result.sum(axis=1)

array([1., 1., 1., 1.])